# Input argm for base image name
ARG QIMSDK_ARG_IMAGE_NAME

# QIMSDK debug development Image
FROM ${QIMSDK_ARG_IMAGE_NAME}-aiml AS qimsdk_dbg_image

# Add root to plugdev group
RUN usermod -aG plugdev root

# Set base directory
ENV QIMSDK_BASE_DIR=/mnt/work
ENV QIMSDK_TMP_DIR=${QIMSDK_BASE_DIR}/tmp
RUN mkdir -p ${QIMSDK_TMP_DIR}

# Add supported targets files
COPY targets ${QIMSDK_TMP_DIR}/targets

# meta-qti-gst: Add
COPY tmp/meta-qti-gst /mnt/work/download/repo/meta-qti-gst

RUN echo "[url \"file:///mnt/work/download/repo/meta-qti-gst\"]                                    \
        insteadOf = https://git.codelinaro.org/clo/le/meta-qti-gst.git"                            \
        >> /etc/gitconfig

# gst-plugins-qti-oss: Add
COPY tmp/gst-plugins-qti-oss /mnt/work/download/repo/gst-plugins-qti-oss

RUN echo "[url \"file:///mnt/work/download/repo/gst-plugins-qti-oss\"] insteadOf =                 \
        https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/gst-plugins-qti-oss.git" \
        >> /root/.gitconfig

# Add development image scripts
ENV QIMSDK_SCRIPTS=${QIMSDK_BASE_DIR}/scripts/
COPY scripts-dbg/dev_sync.sh ${QIMSDK_SCRIPTS}/dev_sync.sh

# Change workdir back to base dir from downloads dir
WORKDIR ${QIMSDK_BASE_DIR}

# Set artifacts save Docker_image_path
ARG QIMSDK_ARG_DOCKER_IMAGE_PATH
ENV QIMSDK_DOCKER_IMAGE_PATH=${QIMSDK_ARG_DOCKER_IMAGE_PATH}

# Set artifacts push device id
ARG QIMSDK_ARG_DEVICE_ID
ENV QIMSDK_DEVICE_ID=${QIMSDK_ARG_DEVICE_ID}

# Set device container name
ARG QIMSDK_ARG_CONTAINER_NAME
ENV QIMSDK_CONTAINER_NAME=${QIMSDK_ARG_CONTAINER_NAME}
