# QIMSDK debug development Image
FROM debian:trixie-slim AS qimsdk_dbg_image

# Add root to plugdev group
RUN usermod -aG plugdev root

# Set base directory
ENV QIMSDK_BASE_DIR=/mnt/work
ENV QIMSDK_REPO_DOWNLOAD_DIR=${QIMSDK_BASE_DIR}/download/repo
ENV QIMSDK_TMP_DIR=${QIMSDK_BASE_DIR}/tmp
ENV QIMSDK_DOCKER_IMAGE_PATH=${QIMSDK_BASE_DIR}/dev_artifacts
RUN mkdir -p ${QIMSDK_DOCKER_IMAGE_PATH}
RUN mkdir -p ${QIMSDK_TMP_DIR}

# Add supported targets files
COPY targets ${QIMSDK_TMP_DIR}/targets

# camera-service: Add (open-source camera-service repository (gst-plugins-imsdk dependency))
COPY tmp/camera-service ${QIMSDK_REPO_DOWNLOAD_DIR}/camera-service

RUN echo "[url \"file://${QIMSDK_REPO_DOWNLOAD_DIR}/camera-service\"]                              \
        insteadOf = https://github.com/qualcomm/camera-service.git"                                \
        >> /etc/gitconfig

# gst-plugins-imsdk: Add
COPY tmp/gst-plugins-imsdk ${QIMSDK_REPO_DOWNLOAD_DIR}/gst-plugins-imsdk

RUN echo "[url \"file://${QIMSDK_REPO_DOWNLOAD_DIR}/gst-plugins-imsdk\"] insteadOf =               \
        https://github.com/qualcomm/gst-plugins-imsdk.git"                                         \
        >> /etc/gitconfig

COPY tmp/solutions-microservices ${QIMSDK_REPO_DOWNLOAD_DIR}/solutions-microservices

RUN echo "[url \"file://${QIMSDK_REPO_DOWNLOAD_DIR}/solutions-microservices\"] insteadOf =         \
        https://git.codelinaro.org/clo/le/solutions-microservices"                                 \
        >> /etc/gitconfig

# Add development image scripts
ENV QIMSDK_SCRIPTS=${QIMSDK_BASE_DIR}/scripts/
COPY scripts-dbg/common.sh ${QIMSDK_SCRIPTS}/common.sh
COPY scripts-dbg/dev_sync.sh ${QIMSDK_SCRIPTS}/dev_sync.sh

# Change workdir back to base dir from downloads dir
WORKDIR ${QIMSDK_BASE_DIR}
