#!/bin/sh

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Use a modules directory which doesn't exist so we don't load random things
# which may then get deleted (or their dependencies) and potentially segfault
export GIO_MODULE_DIR=FIXMESTAGINGDIRTARGET/usr/lib/gio/modules-dummy

PSEUDO_UNLOAD=1 qemu-aarch64 -r 5.15  -L FIXMESTAGINGDIRTARGET -E LD_LIBRARY_PATH=$GIR_EXTRA_LIBS_PATH:.libs:FIXMESTAGINGDIRTARGET//usr/lib:FIXMESTAGINGDIRTARGET//usr/lib  "$@"
if [ $? -ne 0 ]; then
    echo "If the above error message is about missing .so libraries, then setting up GIR_EXTRA_LIBS_PATH in the recipe should help."
    echo "(typically like this: GIR_EXTRA_LIBS_PATH=\"$""{B}/something/.libs\" )"
    exit 1
fi
